runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: web-profile/Me.html
    upload: web-profile/Me.html
  - url: /(.*)
    static_files: web-profile/\1
    upload: web-profile/(.*)
